// This is a data.js file with some of my projects used in the projects page
export const data = [
  {
    id: 1,
    title: "Itunes Search App",
    desc: "React JS,Node JS,Express JS project using itunes search API",
    image: "itunes.png",
    website: "https://itunes-search-client.herokuapp.com/",
    github: "https://github.com/Therealblackgold/L2T21-itunes-search-app",
  },
  {
    id: 2,
    title: "Memory Game",
    desc: "React JS Dinosaur themed memory game,with self timer",
    image: "dinosaur.png",
    website: "https://dinosaur-land.herokuapp.com/",
    github: "https://github.com/Therealblackgold/L2T12-React-Memory-Game",
  },
  {
    id: 3,
    title: "Online Store Project",
    desc: "Shopping cart app with HTML5, CSS, JavaScript",
    image: "project1.png",
    website: "https://phenomenal-toffee-687788.netlify.app/index.html",
    github: "https://github.com/Therealblackgold/L1T15-online-store-app",
  },
  {
    id: 4,
    title: "Multi User Todo",
    desc: "MERN Stack Todo app with JWT Authentication.",
    image: "jwt.png",
    website: "#",
    github: "https://github.com/Therealblackgold/L3T09-mern-jwt-auth",
  },
  {
    id: 5,
    title: "Car Management",
    desc: "MERN Stack crud project.",
    image: "crud.png",
    website: "#",
    github: "https://github.com/Therealblackgold/L3T07-mern-crud-car-app",
  },
  {
    id: 6,
    title: "The Red Dragon",
    desc: "React JS Dragon theme random card game",
    image: "dragon-game.png",
    website: "https://gautancholo-card-game.netlify.app",
    github: "https://github.com/Therealblackgold",
  },
  {
    id: 7,
    title: "$ Currency Convertor",
    desc: "Convert USD to ZAR/GBP/EUR React JS.",
    image: "currency.png",
    website: "https://gautancholo-card-game.netlify.app",
    github: "https://github.com/Therealblackgold",
  },
  {
    id: 8,
    title: "XYZ CAFE",
    desc: "Fast Food Website React JS UI.",
    image: "food1.png",
    website: "https://gautancholo-xyz-cafe.netlify.app/",
    github: "https://github.com/Therealblackgold",
  },
];
