import Head from "next/head";
import React from "react";
import Circle from "../components/Circle";
/*This page renders the about page which tells a visitor a bit more about myself*/

const AboutMe = () => {
  return (
    <>
      <Head>
        <title>Gauta Ncholo | About </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className="about" id="about">
        <h1 className="section-heading">
          about <span>me</span>
        </h1>
        <div className="content">
          <p>
            I learned programming in many different ways from taking online
            courses and reading books Im currently enrolled in a fulltime
            fullstack web development course with Hyperion Dev. I conceder my a
            self taught programmer with a clear road map and high evaluation
            standards set by an institution like Hyperion Dev I can finally get
            the support I need towards starting my carrier in tech. Ive included
            a summarized list of my current and completed courses.
          </p>
          <div className="education">
            <h3 className="section-subHeading">EDUCATIONAL HISTORY</h3>
            <ul>
              <li>Complete Python Bootcamp: Zero to Hero By Jose Portilla.</li>
              <li>
                Python &amp; Django Full Stack Web Developer Bootcamp By Jose
                Portilla
              </li>
              <li>
                Django 2.2 &amp; Python|The Ultimate Web Development Bootcamp By
                Nick Walter
              </li>
              <li>Complete JavaScript Course By Jonas Schmedtmann</li>
              <li>
                Build Responsive Real World Websites With HTML 5 and CSS By
                Jonas Schmedtmann
              </li>
              <li>Advanced CSS and Sass By Jonas Schmedtmann</li>
              <li>Hyperion Dev Fullstak Web Development Bootcamp</li>
            </ul>
          </div>
          <a
            href="/img/gauta ncholo-resume.pdf"
            className="btn cta btn"
            download="Gauta-Ncholo-Resume"
            target="_blank"
          >
            download cv
            <i className="bi bi-arrow-down-circle-fill" />
          </a>
        </div>

        <style jsx>{`
          li {
            margin: -10px;
          }

          .about .list-items {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            justify-content: center;
            align-items: center;
          }

          .about {
            text-align: center;
            margin-bottom: 5rem;
          }
          .about .content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            gap: 20px;
            flex-wrap: wrap;
          }

          .about .content p {
            padding: 10px;
            line-height: 30px;
            font-family: "Open Sans", sans-serif;
            font-size: 16px;
            font-weight: 500;
            max-width: 800px;
            text-align: center;
          }

          .about .content ul {
            line-height: 40px;
          }

          section li::before {
            content: "";
            display: inline-block;
            background-image: url(./img/dot.png);
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            width: 0.5em;
            height: 0.5em;
            margin-right: 0.3rem;
          }
        `}</style>
      </section>
    </>
  );
};

export default AboutMe;
