import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { data } from "../data";
/*This page renders the projects page using Next JS getStaticProps to get 
projects from a data.js file in the root directory which helped cleaning
up repeated code*/

export const getStaticProps = async () => {
  // declaring projects
  const projects = data;
  // returning projects object as props so they can be used in the  Projects component.
  return {
    props: { projects },
  };
};

// Then below destructure projects and map through them to return a card for each project.
const Projects = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Gauta Ncholo | Projects </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className="portfolio" id="portfolio">
        <h1 className="section-heading" style={{ marginBottom: "1.5rem" }}>
          <span>My</span> Projects
        </h1>
        <div className="card-container">
          {projects.map((project) => (
            <div key={project.id} className="card">
              <div className="card-image">
                <Image
                  src={`/img/${project.image}`}
                  alt={project.title}
                  width="400px"
                  height="200px"
                  objectFit="cover"
                />
              </div>
              <div className="content">
                <h3>{project.title}</h3>
                <p>{project.desc}</p>
                <div className="project-link">
                  <Link href={project.website} target="_blank" passHref>
                    <a target="_blank">Live project</a>
                  </Link>
                </div>
                <Link href={project.github} target="_blank">
                  <a target="_blank" className="btn">
                    view <i className="bi bi-github" />
                  </a>
                </Link>
              </div>
            </div>
          ))}
        </div>

        <style jsx>{`
          .portfolio .card-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 20px;
            margin-bottom: 10rem;
          }

          .portfolio .card-container .card {
            border-radius: 10px;
            border: 1px solid var(--grey-color);
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin-bottom: 20px;
          }

          .portfolio .card-container .card .content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            gap: 10px;
            padding: 10px;
            text-align: center;
          }

          .portfolio .card-container .card .content p {
            width: 310px;
          }

          .portfolio .card-container .card img {
            border-radius: 10px 10px 0 0;
            width: 100%;
          }

          .portfolio .card-container .card img:hover {
            opacity: 25%;
          }

          .portfolio .card-container .card h3 {
            font-size: 20px;
          }

          .portfolio .card-container .card p {
            font-family: "Open Sans", sans-serif;
            font-size: 16px;
            font-weight: 500;
          }

          .project-link {
            color: var(--primary-color);
            text-decoration: underline;
          }
        `}</style>
      </section>
    </>
  );
};

export default Projects;
